-- Plugin setup
require("lazy").setup({
    require("plugins.notify"),

    -- Base dependencies / standalone plugins
    { "nvim-lua/plenary.nvim" },
    { "jssee/vim-delight" },
    { "b0o/schemastore.nvim" },

    -- Configured plugins
    require("plugins.onedarkpro"),
    require("plugins.comment-nvim"),
    require("plugins.indent-blankline"),
    require("plugins.window-picker"),
    require("plugins.which-key"),
    require("plugins.treesitter"),
    require("plugins.rainbow-delimiters"),
    require("plugins.neotree"),
    require("plugins.undotree"),
    require("plugins.toggleterm"),
    require("plugins.mini-surround"),
    require("plugins.dashboard-nvim"),
    require("plugins.fidget"),
    require("plugins.flash"),
    require("plugins.dressing"),
    require("plugins.lazydev"),
    require("plugins.nvim-lspconfig"),
    require("plugins.conform"),
    require("plugins.nvim-cmp"),
    require("plugins.nvim-ufo"),
    require("plugins.telescope"),
    require("plugins.nvim-autopairs"),
    require("plugins.aerial"),
    require("plugins.neotest"),
    require("plugins.iron-nvim"),
    require("plugins.crates-nvim"),
    require("plugins.csvview"),
    require("plugins.arduino-nvim"),
    require("plugins.venv-selector"),
    require("plugins.lualine"),
})
